### ISSUE TITLE
First stable release

### ISSUE THREAD

**Issue by mburns** [goru97/ele-cassandra#3]
# TODO
- [x] metadata - #1 
- [x] lint - #2 
- [x] Test coverage
  - [x] unit test: valid config file(s) written
  - [x] integration test: valid package downloaded, service created. 
- [x] Get CI working on each commit: run tests, lint code
- [x] tag release for Berkshelf usage

**Comment by goru97** [comment]
Done!
